### ISSUE TITLE
Will there be updates to be compatible with the latest compiler?

### ISSUE THREAD

**Issue by xin-jin** [tov/shcaml#1]
I tried using opam to install this package, and it says OCaml 3.12.1 is needed.

**Comment by tov** [comment]
Unfortunately, I have no plans to update Shcaml at this time. However, if you think there’s something you want to use it for, we could discuss whether it would be suitable and maybe I could help you fix it.

**Comment by Armael** [comment]
See the latest release, available for ocaml 4.02 and later :). Happy hacking!
