### ISSUE TITLE
companion paper link dead

### ISSUE THREAD

**Issue by progman1** [tov/shcaml#8]
it's dead, Zed

**Comment by tov** [comment]
Thanks for the report. Do you mean the link to http://users.eecs.northwestern.edu/~jesse/pubs/caml-shcaml/ from `README.md`? That link works for me, though it redirects to http://users.cs.northwestern.edu/~jesse/pubs/caml-shcaml/. I’ve updated it to point directly there. Does it work for you now?

**Comment by progman1** [comment]
it does! thanks
